services:
  - type: worker
    name: jururu-discord-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python jrr.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY_1
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GEMINI_API_KEY_3
        sync: false
      - key: GEMINI_API_KEY_4
        sync: false
      - key: GEMINI_API_KEY_5
        sync: false
      - key: GEMINI_API_KEY_6
        sync: false
